version: '3.8'
services:
  mysql:
    image: mysql:8.0.37
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 6040
    volumes:
      - transacoes-bancarias:/var/lib/mysql

volumes:
  transacoes-bancarias: